### ISSUE TITLE
ロードマップ（トップ）ページ作成

### ISSUE THREAD

**Issue by takecchi** [cuculus-dev/cuculus-roadmap#28]
## Community Issue
cuculus-dev/.github#10

## 概要
トップページの作成
 figma: https://www.figma.com/file/pshVsQPL2AQ802eZTgjttZ/Cuculus.Roadmap?type=design&node-id=0-1&mode=design&t=CVkBddr6e3yqDjJF-0

## 備考
デザイン上の残作業があるため、作業開始前に @AyumuAkimoto に確認

デザイン
- [x] タイトル下文書
- [x] GitHubリンク
- [x] issuesのチケットっぽいの

また、作業が多いのでタスクを複数に分け（小タスク）、新規issue作成を推奨

一旦lightデザイン(figma上左側)のものだけ考慮できていれば良いものとする。
 
## Todo
- [x] cuculus-dev/.github#18
- [x] #41
- [x] #42
- [x] レスポンシブ対応(スマホで見た時にデザインが崩れない)
- [x] github APIからマイルストーンを取得し、画面に描画されること（取得部分はサンプル実装済み）
- [x] #40
- [x] figmaのデザインと見比べて80%くらい合ってれば🆗

**Comment by takecchi** [comment]
@AyumuAkimoto 
ロゴ下の文章とボタンが必要だと思うのでそちらの修正をお願いします。

実際にマイルストーンを当てた時のイメージの作成お願いします。

**Comment by AyumuAkimoto** [comment]
@KND-T 
mainブランチから最新の状態を取り込んでpage.tsでレイアウトの最終調整をお願いします。
余白だったりMilestonesの幅感とかの微調整をしてfigmaのデザインと合う状態になるのがゴールです。
