### ISSUE TITLE
背景に雲

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus-roadmap#29]
- [x] レスポンシブ対応
- [ ] ~z-indexを使って奥行きを考える~ 時間がかかりすぎるので今回は実施しない
- [ ] ~雲が一枚一枚SVGとして表示されていること~ 時間がかかりすぎるので今回は実施しない

**Comment by takecchi** [comment]
個々でSVGをスタイリングするやり方だと、あちらを立てればこちらが立たずでしんどいので、速度を優先しバックグラウンド画像に。

SVGでなんやかんややった証跡はアーカイブとして置いておくので、必要になったら参考に
https://github.com/cuculus-dev/cuculus-roadmap/tree/archive/issues-29-cloud
