### ISSUE TITLE
ヘッダーコンポーネントの作成

### ISSUE THREAD

**Issue by takecchi** [cuculus-dev/cuculus-roadmap#3]
## Community Issue
cuculus-dev/.github#10

## 概要
ヘッダーとヘッダーに関係するコンポーネントの作成
コンポーネントは必要に応じて追加。

以下はメモ

### Atoms
- SvgLink ... svgのアイコンクリックしたら遷移できるようなやつ
- LinkButton ... クリックでリンク先に飛べるやつ

### Molecule
- Cuculusのロゴ ... クリックで`/`に遷移(デザインがまだ)
- Githubアイコンボタン ... オクトキャットの画像クリックするとcuculus-devに飛べる感じ(画像は公式にあるかな)

## Header
[Cuculusのロゴ] [community] [真ん中に何もないスペース] [Githubアイコン]

こんな感じのイメージ

**Comment by takecchi** [comment]
vercelのサイトのヘッダいい感じ(非ログイン状態じゃないと見れないかも)
かっこいい
https://vercel.com/

**Comment by takecchi** [comment]
Githubへのリンク先は https://github.com/cuculus-dev
実装イメージは[MUIのドキュメント](https://mui.com/)のヘッダーの右にあるような感じでオクトキャットアイコン

**Comment by kawanolk** [comment]
> Githubへのリンク先は https://github.com/cuculus-dev 実装イメージは[MUIのドキュメント](https://mui.com/)のヘッダーの右にあるような感じでオクトキャットアイコン

GitHubのアイコンは公式で配布してそうhttps://github.com/logos

**Comment by takecchi** [comment]
ボタン参考
https://mui.com/material-ui/react-button/

**Comment by takecchi** [comment]
@kawanolk @KND-T 
https://www.figma.com/file/pshVsQPL2AQ802eZTgjttZ/Cuculus.loadmap?type=design&node-id=0%3A1&mode=design&t=Yo101KMKA44c6bN5-1
デザイン

**Comment by takecchi** [comment]
@AyumuAkimoto 
別の対応にも影響あるからmainにマージしました。
デザイン問題ないか確認お願いします。
