### ISSUE TITLE
MilestonesからIssuesを取得する方法の調査と実装

### ISSUE THREAD

**Issue by takecchi** [cuculus-dev/cuculus-roadmap#40]
## 概要
[Milestones List](https://docs.github.com/ja/rest/issues/milestones?apiVersion=2022-11-28#list-milestones)からマイルストーンの一覧は取得できるが、マイルストーンに紐付いているIssuesまでは取得できない。  
取得したマイルストーンから別のAPIを叩くことで取得できると思われるので、それの調査と実装を行う。

## 参考
実際に叩くAPIは以下
https://api.github.com/repos/cuculus-dev/cuculus-community/milestones

**Comment by takecchi** [comment]
## 調査
[Issues List](https://docs.github.com/en/free-pro-team@latest/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues)のクエリパラメータ`milestone`指定でいけそう？

https://api.github.com/repos/cuculus-dev/cuculus-community/issues?milestone=2

**Comment by kawanolk** [comment]
調べた結果
GItHubのAPIと使用するためのとAPIリクエストの作成は必要。
->REST APIを使用するっぽいのでAPIは問題なし
->マイルストーンからissuesを取得するにはHTTPクライアントまたはサーバーサイドからのAPIリクエストが必要そう
-->HTTPクライアントまたはサーバーサイドのAPIリクエスト方法として`fetch` `Axios`がある

**Comment by kawanolk** [comment]
以下参考サイト
https://qiita.com/morry_48/items/3dda89b03c29537a5f86
https://qiita.com/sotasato/items/31be24d6776f3232c0c0
https://qiita.com/s_taro/items/30114cfa370aac6c085f
