### ISSUE TITLE
issuesを表示するカードコンポーネント

### ISSUE THREAD

**Issue by AyumuAkimoto** [cuculus-dev/cuculus-roadmap#41]
- [x] レスポンシブ対応
- [x] issuesの進行状況が表示できる
- [x] issuesのタイトルが表示できる
- [x] issuesのマイルストーンを表示できる（タグ風のやつで今後github上のラベルとかも反映できると良さそう）
- [x] issuesの説明文が表示できる

※説明文については表示しないか長くなると見た目見づらくなりそうだし興味ある人はgithub見に来ると思うのである程度の行数で区切って…とかで省略するやつでもいいかもしれないと思ってるけどどうですか。

**Comment by takecchi** [comment]
> ※説明文については表示しないか長くなると見た目見づらくなりそうだし興味ある人はgithub見に来ると思うのである程度の行数で区切って…とかで省略するやつでもいいかもしれないと思ってるけどどうですか。

Phase（今後バージョンになるかもだけど）は大まかな目標だから概要表示するでいいと思う。
改行コードそのまま使えば見づらいってことにもならないと思うし。

Issuesに書いてあるような個々のタスクに関する説明は見たところでだし、いらないと思う。

**Comment by AyumuAkimoto** [comment]
ロードマップがしっかり動き出すことを想定してissuesの書式も上に説明文を記載するようにフォーマット化したほうが表示するのに都合良かったりするかな

**Comment by kawanolk** [comment]
デザインの修正を反映する

- [ ] マイルストーンとIssuesの幅を詰める 
- [ ] スケルトンの作成
