### ISSUE TITLE
VSCodeの設定共通化

### ISSUE THREAD

**Issue by takecchi** [cuculus-dev/cuculus-roadmap#6]
## 概要
VSCodeを使用して開発するメンバー向けに以下の設定を行う

- 自動でインポートした際に相対パスではなくエイリアス(@/*)を使った絶対パスになる
- 自動でprettierを使ったフォーマットがかかるようになる
- 以下の拡張機能をリコメンドする
  - Prettier
  - vscode-styled-components
  - ESLint

## Todo
- [x] VSCodeの自動インポートで絶対パスが入るようになっていること

**Comment by kawanolk** [comment]
対応しました
